[package]
name = "anti-mouse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mouse-rs = "0.4"
winit = "0.27.5"
device_query = "1.1.2"
serde_json = "1.0"
